/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rubrica;

import org.junit.Test;
import org.rubrica.App;

import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void emptyTest() {
        
    }
}
