/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rubrica;


public class App {

    public static void main(String[] args) {

        DataManager dm = new DataManager();

        FinestraPrincipale fp = new FinestraPrincipale(dm);
        
        
    }
}
