/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rubrica;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        DataManager dm = new DataManager();

        FinestraPrincipale fp = new FinestraPrincipale(dm);
        
        
    }
}
