/*
 * This source file was generated by the Gradle 'init' task
 */
package org.rubrica;


public class App {

    public static void main(String[] args) {
        DataManager dm = null;
        try{
            dm = new DataManager();
        } catch (Exception e) {
            System.err.println("Errore durante l'inizializzazione del DataManager: " + e.getMessage());
            return;
        }

        new FinestraPrincipale(dm);
        
        
    }

    
}
